### PR TITLE
fix: unit tests

### LINKED ISSUE #6297: [🐛 Bug]: Unit tests failing (see tests from PR #6296)
**Describe the bug**
Hi,

Three unit tests are currently failing due to calling a NoneType object and importing a non-existing function.

Logs:

`FAILED tests/test_incidents.py::test_incident_dto_is_visible_to_db - AttributeError: 'NoneType' object has no attribute 'order'
FAILED tests/test_keep_provider_notify_alert_none.py::test_notify_alert_with_none_alert_results_no_crash - AttributeError: <module 'keep.providers.keep_provider.keep_provider' from '/home/runner/work/keep/keep/keep/providers/keep_provider/keep_provider.py'> does not have the attribute 'Pusher'
FAILED tests/test_keep_provider_notify_alert_none.py::test_notify_alert_with_none_alert_results_and_alert_param - AttributeError: <module 'keep.providers.keep_provider.keep_provider' from '/home/runner/work/keep/keep/keep/providers/keep_provider/keep_provider.py'> does not have the attribute 'Pusher'`

**To Reproduce**

1. Submit a PR that runs the unit tests
2. Wait for the tests to complete.
3. See error

**Expected behavior**
All unit tests succeeding if the code is OK.

**Screenshots**
See unit tests from PR #6296

**Additional context**

### PR DESCRIPTION
**Pull request by Walkablenormal**
Closes #6297

## 📑 Description

Hi,

In my PR #6296 I've noticed the unit-tests failing. This PR contain the fixes for the failing tests.

The first issue was importing and mapping the severity-field in one of the tests.
The second issue was calling a function that has been replaced by another function.

## ✅ Checks

- [X] My pull request adheres to the code style of this project
- [N] My code requires changes to the documentation
- [N] I have updated the documentation as required
- [X] All the tests have passed

### CODE REVIEW

**Comment by Walkablenormal** [comment]
Hi,

I think this is ready for review too. E2E test seems to be kinda flakey.

@shahargl can you review and PR this please?

Thanks!

**Review by shahargl — APPROVED** [review]
lgtm
