### ISSUE TITLE
[🐛 Bug]: Unit tests failing (see tests from PR #6296)

### ISSUE THREAD

**Issue by Walkablenormal** [keephq/keep#6297]
**Describe the bug**
Hi,

Three unit tests are currently failing due to calling a NoneType object and importing a non-existing function.

Logs:

`FAILED tests/test_incidents.py::test_incident_dto_is_visible_to_db - AttributeError: 'NoneType' object has no attribute 'order'
FAILED tests/test_keep_provider_notify_alert_none.py::test_notify_alert_with_none_alert_results_no_crash - AttributeError: <module 'keep.providers.keep_provider.keep_provider' from '/home/runner/work/keep/keep/keep/providers/keep_provider/keep_provider.py'> does not have the attribute 'Pusher'
FAILED tests/test_keep_provider_notify_alert_none.py::test_notify_alert_with_none_alert_results_and_alert_param - AttributeError: <module 'keep.providers.keep_provider.keep_provider' from '/home/runner/work/keep/keep/keep/providers/keep_provider/keep_provider.py'> does not have the attribute 'Pusher'`

**To Reproduce**

1. Submit a PR that runs the unit tests
2. Wait for the tests to complete.
3. See error

**Expected behavior**
All unit tests succeeding if the code is OK.

**Screenshots**
See unit tests from PR #6296

**Additional context**
